name: BrainNetworkTransformer
alias: bnt
sizes: [360, 100]  # Note: The input node size should not be included here
pooling: [false, true]
pos_encoding: none  # identity, none
orthogonal: true
freeze_center: true
project_assignment: true
pos_embed_dim: 360
feature_dim: 800
patience: 35
min_delta: 0.001