use_grl: false
grl_lambda: 1.0
domain_loss_weight: 1.0
hidden_dim: 128
grl_schedule: dann       # "cosine" | "linear" | "dann"
grl_gamma: 10.0
grl_max_lambda: 1.0 
grl_warmup_epochs: 3
grl_ramp_epochs: 10