program: run_loso.py
method: bayes
metric:
  name: val_auc
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 10
  max_iter: 50
  s: 2

parameters:
  models.name:
    values: [SpatioTemporalModel, BrainGNN, BrainNetworkTransformer]

  domain_adaptation.use_grl:
    values: [true, false]

  domain_adaptation.grl_lambda:
    min: 0.0
    max: 1.0

  domain_adaptation.domain_loss_weight:
    min: 0.0
    max: 1.0

  training.lr:
    values: [0.0005, 0.001]

  training.seed:
    values: [42, 1337]