defaults:
  - _self_
  - dataset: abide
  - models: bnt # bnt, dsam, braingnn
  - optimizer: adam
  - training: training_configs
  - datasz: 100p
  - preprocess: non_mixup
  - logging: logging
  - sweep: sweep
  - domain_adaptation: domain_adaptation

repeat_time: 1
log_path: result
save_learnable_graph: False
local_host: false
# wandb
wandb_entity: eggroup
project: "Domain Adaptation"